"""Non-interactive setup generation for modal-mcp.

This module implements ``modal-mcp setup --yes``, which generates:

- A private HMAC signing key in ``<secrets_dir>/<signing_key_name>``
- A local ``.env`` file that references the key and supplies minimal
  server settings

Rules
-----
- No Modal credential material is ever written (``MODAL_TOKEN_ID``,
  ``MODAL_TOKEN_SECRET``, ``MODAL_TOKEN_ID_FILE``,
  ``MODAL_TOKEN_SECRET_FILE``).
- ``MODAL_ENVIRONMENT`` is never written, so no default environment is
  silently pinned.
- Existing signing keys are preserved by default (idempotent).
- Symlink targets are refused for both the key file and the env file.
"""

from __future__ import annotations

import contextlib
import os
import secrets
import tempfile
from dataclasses import dataclass
from pathlib import Path

from modal_mcp.setup_files import SetupFilesError, write_secret

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: HMAC key length in bytes (32 bytes → 256-bit key for HMAC-SHA256).
_SIGNING_KEY_BYTES: int = 32

#: Default key ID embedded in generated signing key entries.
_DEFAULT_KID: str = "k1"

#: Default allowed origin (matches the default ``MODAL_MCP_HTTP_BIND``).
_DEFAULT_ALLOWED_ORIGIN: str = "http://127.0.0.1:8765"

#: Default .env filename (resolved relative to CWD at call time).
DEFAULT_ENV_FILE: Path = Path(".env")

#: Default secrets directory (resolved relative to CWD at call time).
DEFAULT_SECRETS_DIR: Path = Path(".secrets")

#: Default signing key filename inside the secrets directory.
DEFAULT_SIGNING_KEY_NAME: str = "signing-key.txt"

#: Env-var names that must never appear in a setup-generated .env file.
#: Writing them would silently adopt Modal credentials or pin an environment.
FORBIDDEN_SETUP_ENV_KEYS: frozenset[str] = frozenset(
    {
        "MODAL_TOKEN_ID",
        "MODAL_TOKEN_SECRET",
        "MODAL_TOKEN_ID_FILE",
        "MODAL_TOKEN_SECRET_FILE",
        "MODAL_ENVIRONMENT",
    }
)


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class SetupResult:
    """Outcome of a :func:`run_setup` invocation."""

    #: Resolved absolute path to the ``.env`` file.
    env_file: Path
    #: Resolved absolute path to the signing key file.
    signing_key_file: Path
    #: ``True`` when the signing key was freshly generated; ``False`` when a
    #: pre-existing key was preserved.
    signing_key_created: bool
    #: ``True`` when the ``.env`` file was freshly written; ``False`` when a
    #: pre-existing file was preserved.
    env_created: bool


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _generate_signing_key_material(kid: str = _DEFAULT_KID) -> str:
    """Return a fresh ``kid:hex`` HMAC-SHA256 signing key string."""
    key_bytes = secrets.token_bytes(_SIGNING_KEY_BYTES)
    return f"{kid}:{key_bytes.hex()}"


def _build_env_content(signing_key_file: Path) -> str:
    """Return the content for a freshly generated ``.env`` file.

    The file only writes keys required for the server to start (signing key
    reference and allowed origins).  All Modal credential variables and
    ``MODAL_ENVIRONMENT`` are intentionally omitted.
    """
    lines = (
        "# modal-mcp local configuration",
        "# Generated by 'modal-mcp setup --yes'.",
        "#",
        "# DO NOT add MODAL_TOKEN_ID, MODAL_TOKEN_SECRET, or MODAL_ENVIRONMENT here.",
        "# Modal credentials are read from ~/.modal.toml or injected at runtime.",
        "#",
        f"MODAL_MCP_SIGNING_KEY_FILE={signing_key_file}",
        f"MODAL_MCP_ALLOWED_ORIGINS={_DEFAULT_ALLOWED_ORIGIN}",
        "",
    )
    return "\n".join(lines)


def _write_env_idempotent(path: Path, content: str) -> bool:
    """Atomically write a dotenv file, preserving existing content.

    Unlike :func:`~modal_mcp.setup_files.write_secret`, this helper does
    **not** tighten parent-directory permissions, making it suitable for files
    placed in a shared project root.

    The parent directory is created (``parents=True``) when it does not exist,
    but its mode is left unchanged.

    Returns
    -------
    bool
        ``True`` when the file was freshly written; ``False`` when a
        pre-existing file was preserved.

    Raises
    ------
    SetupFilesError
        If *path* is a symlink (checked both before and after the write to
        guard against racing renames).
    """
    if path.is_symlink():
        msg = f"refusing to write env file: target is a symlink: {path}"
        raise SetupFilesError(msg)

    if path.exists():
        return False  # preserve existing

    path.parent.mkdir(parents=True, exist_ok=True)

    encoded: bytes = content.encode()
    tmp_path: Path | None = None
    try:
        fd, tmp_str = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp_env_")
        tmp_path = Path(tmp_str)
        try:
            if os.name == "posix":
                # Restrict before writing so data is never visible to other users.
                os.chmod(fd, 0o600)
            os.write(fd, encoded)
        finally:
            os.close(fd)

        # Race-condition guard: re-check that the destination hasn't become a symlink.
        if path.is_symlink():
            msg = f"refusing to write env file: target became a symlink: {path}"
            raise SetupFilesError(msg)

        tmp_path.replace(path)
        tmp_path = None

    finally:
        if tmp_path is not None:
            with contextlib.suppress(OSError):
                tmp_path.unlink()

    if os.name == "posix":
        path.chmod(0o600)

    return True


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_setup(
    *,
    env_file: Path | str = DEFAULT_ENV_FILE,
    secrets_dir: Path | str = DEFAULT_SECRETS_DIR,
    signing_key_name: str = DEFAULT_SIGNING_KEY_NAME,
) -> SetupResult:
    """Generate a ``.env`` file and an HMAC signing key for local setup.

    Both artifacts are preserved when they already exist — the function is
    fully idempotent.

    Parameters
    ----------
    env_file:
        Destination for the ``.env`` file.  Resolved to an absolute path at
        call time.  Defaults to ``.env`` in the current working directory.
    secrets_dir:
        Directory for private signing key material.  Created with mode
        ``0o700`` on POSIX when it does not exist.  Defaults to ``.secrets``
        in the current working directory.
    signing_key_name:
        Filename for the signing key inside *secrets_dir*.

    Returns
    -------
    SetupResult
        Resolved paths and freshness flags for both artifacts.

    Raises
    ------
    SetupFilesError
        If the signing key path or the env file path is (or becomes) a
        symlink.
    """
    # Use .absolute() (not .resolve()) so that a symlink at the destination
    # is NOT followed.  .resolve() would silently follow the symlink chain and
    # deliver a non-symlink target path to write_secret / _write_env_idempotent,
    # bypassing their symlink guard.  .absolute() makes the path absolute by
    # prepending CWD when relative, without touching symlinks in any component.
    env_path = Path(env_file).expanduser().absolute()
    key_path = (Path(secrets_dir).expanduser() / signing_key_name).absolute()

    # Capture pre-existing state *before* writing, so that the result flags
    # reflect what was on disk at call time rather than what we produced.
    # A symlink counts as "does not exist" because write_secret (or
    # _write_env_idempotent) will raise SetupFilesError before we return.
    key_existed = key_path.exists() and not key_path.is_symlink()
    env_existed = env_path.exists() and not env_path.is_symlink()

    # 1. Write signing key (atomic, private-mode, idempotent via overwrite=False).
    write_secret(key_path, _generate_signing_key_material())

    # 2. Write .env (atomic, mode 0o600, idempotent, no parent chmod).
    _write_env_idempotent(env_path, _build_env_content(key_path))

    return SetupResult(
        # Use the absolute (non-symlink-following) paths for consistency.
        # Both writes succeeded (or the paths were preserved), so these paths
        # refer to real files on disk.
        env_file=env_path,
        signing_key_file=key_path,
        signing_key_created=not key_existed,
        env_created=not env_existed,
    )


__all__ = [
    "DEFAULT_ENV_FILE",
    "DEFAULT_SECRETS_DIR",
    "DEFAULT_SIGNING_KEY_NAME",
    "FORBIDDEN_SETUP_ENV_KEYS",
    "SetupResult",
    "run_setup",
]
